#!/bin/bash
#
# Tool analyses nginx log ang prints info about top 5 IP addresses with the most requests,
# top 5 most requested paths, top 5 response status codes and top 5 user agents.
#
# Usage: log-analyser <nginx-log-file>

top_ips() {
  awk '{print $1}' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{printf "%s - %d requests\n", $2, $1}'
}

top_paths() {
  awk '{print $7}' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{printf "%s - %d requests\n", $2, $1}'
}

top_codes() {
  grep -o ' [0-9]\{3\} ' "$1" | sort | uniq -c | sort -nr | head -n 5 | awk '{printf "%s - %d requests\n", $2, $1}'
}

top_agents() {
  grep -o '"[^"]*"$' "$1" | sort | uniq -c | sort -nr | head -n 5  | awk -F'"' '{printf "%s - %d requests\n", $2, $1}'
}

main() {
  if [ -z "$1" ]; then
    echo "You need to specify the location of the log file."
    echo "Usage: log-analyser <nginx-log-file>"
    exit 1
  else
    printf "Top 5 IP addresses with the most requests:\n"
    printf "%s\n\n" "$(top_ips "$1")"
    printf "Top 5 most requested paths:\n"
    printf "%s\n\n" "$(top_paths "$1")"
    printf "Top 5 response status codes:\n"
    printf "%s\n\n" "$(top_codes "$1")"
    printf "Top 5 user agents:\n"
    printf "%s\n" "$(top_agents "$1")"
  fi
}

main "$1"